package io.rong.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import com.sea_monster.dao.AbstractDao;
import com.sea_monster.dao.AbstractDaoSession;
import com.sea_monster.dao.identityscope.IdentityScopeType;
import com.sea_monster.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class ConversationSession extends AbstractDaoSession {

    private final DaoConfig draftDaoConfig;

    private final DraftDao draftDao;

    public ConversationSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        draftDaoConfig = daoConfigMap.get(DraftDao.class).clone();
        draftDaoConfig.initIdentityScope(type);

        draftDao = new DraftDao(draftDaoConfig, this);

        registerDao(Draft.class, draftDao);
    }
    
    public void clear() {
        draftDaoConfig.getIdentityScope().clear();
    }

    public DraftDao getDraftDao() {
        return draftDao;
    }

}
