package io.rong.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DRAFT.
 */
public class Draft {

    private String id;
    private Integer type;
    private String content;
    private byte[] ext;

    public Draft() {
    }

    public Draft(String id, Integer type) {
        this.id = id;
        this.type = type;
    }

    public Draft(String id, Integer type, String content, byte[] ext) {
        this.id = id;
        this.type = type;
        this.content = content;
        this.ext = ext;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public byte[] getExt() {
        return ext;
    }

    public void setExt(byte[] ext) {
        this.ext = ext;
    }

}
