package com.tongban.im.db.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_TABLE.
 */
public class UserTable {

    private String user_id;
    private String mobile_phone;
    private String nick_name;
    private String portrait_url;
    private String tags;
    private String declaration;

    public UserTable() {
    }

    public UserTable(String user_id) {
        this.user_id = user_id;
    }

    public UserTable(String user_id, String mobile_phone, String nick_name, String portrait_url, String tags, String declaration) {
        this.user_id = user_id;
        this.mobile_phone = mobile_phone;
        this.nick_name = nick_name;
        this.portrait_url = portrait_url;
        this.tags = tags;
        this.declaration = declaration;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getMobile_phone() {
        return mobile_phone;
    }

    public void setMobile_phone(String mobile_phone) {
        this.mobile_phone = mobile_phone;
    }

    public String getNick_name() {
        return nick_name;
    }

    public void setNick_name(String nick_name) {
        this.nick_name = nick_name;
    }

    public String getPortrait_url() {
        return portrait_url;
    }

    public void setPortrait_url(String portrait_url) {
        this.portrait_url = portrait_url;
    }

    public String getTags() {
        return tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public String getDeclaration() {
        return declaration;
    }

    public void setDeclaration(String declaration) {
        this.declaration = declaration;
    }

}
